name: CI Pipeline

on:
  push:
    branches:
      - main
      - stairs
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting CI Pipeline"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Move into Project Directory
        run: cd Rogue

      - name: Build with Maven
        run: mvn clean install
        working-directory: Rogue

      - name: Run Unit Tests
        run: mvn test
        working-directory: Rogue

      - name: Install xvfb (Virtual Display for JavaFX)
        run: sudo apt-get install -y xvfb

      - name: Run the Game (Headless Mode for CI)
        run: xvfb-run --auto-servernum java -jar target/roguegame.jar
        working-directory: Rogue

      - name: Post Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Complete job
        run: echo "CI Pipeline finished!"
