name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          cd Rogue
          mvn clean install

      - name: Run Unit Tests
        run: |
          cd Rogue
          mvn test

      - name: Run the Game (Headless Mode for CI)
        run: |
          cd Rogue
          mvn exec:java -Dexec.mainClass="edu.depaul.rogue.RogueGame"
