name: Build and Test

on:
  push:
    branches:
      - main
      - stairs  # Adjust if you want CI on a different branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Build with Maven
        run: |
          cd Rogue
          mvn clean install -DskipTests
        

      - name: Run Unit Tests
        run: |
          cd Rogue
          mvn test